name: CI

on: [push]

env:
  INPUT_TZ1: Asia
  INPUT_TZ2: Shanghai

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
  
    runs-on: ${{ matrix.os }}

    steps:
    - name: Get the datetime
      id: get_datetime
      uses: ccccmagicboy/get_datetime@master
      with:
        tz1: 'Asia'
        tz2: 'Shanghai'

    - name: Print the datetime
      run: |
        echo ${{ steps.get_datetime.outputs.datetime_str }}-${{ matrix.packaging }}
      shell: bash
