name: CI

on: [push]

env:
  INPUT_TZ1: Asia
  INPUT_TZ2: Shanghai

jobs:
  build:
    strategy:
      matrix:
          os: [windows-2019]
  
    runs-on: windows-latest
    
    steps:
    
    - uses: Jimver/cuda-toolkit@v0.2.4
      id: cuda-toolkit
      with:
        cuda: '11.2.2'
        
    - name: Get current date
      id: get_datetime
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Print the datetime
      run: |
        echo ${{ steps.get_datetime.outputs.date }}-${{ matrix.os }}
      shell: bash
      
