name: CI

on: [push]

env:
  INPUT_TZ1: Asia
  INPUT_TZ2: Shanghai

jobs:
  build:
    strategy:
      matrix:
          os: [windows-2019]
  
    runs-on: windows-latest
    
    steps:
    
    - name: Installing Python
      run: |
          Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.7.7/python-3.7.7-amd64.exe" -OutFile Python3.7.7.exe
          $installer = Start-Process -FilePath Python3.7.7.exe -Wait -PassThru -ArgumentList @("/S");
          $installer.WaitForExit();
