name: CI

on: [push]

env:
  INPUT_TZ1: Asia
  INPUT_TZ2: Shanghai

jobs:
  build:
    strategy:
      matrix:
          os: [windows-2019]
  
    runs-on: windows-latest
    
    steps:
    
    - name: Donwloading LLVM
      run: |
          Invoke-WebRequest -Uri "https://github.com/vovkos/llvm-package-windows/releases/download/llvm-master/llvm-13.0.0-windows-amd64-msvc15-msvcrt.7z" -OutFile llvm.7z
          7z x llvm.7z -ollvm
          rm llvm.7z
          Remove-Item llvm/llvm-13.0.0-windows-amd64-msvc15-msvcrt/bin -Recurse -Force -Confirm:$false
          setx LLVM_ROOT ${{ github.workspace }}/llvm/llvm-13.0.0-windows-amd64-msvc15-msvcrt
          
    - name: Test LLVM
      run: |
          cd ${{ github.workspace }}/llvm/llvm-13.0.0-windows-amd64-msvc15-msvcrt/lib && ls
        
    
