name: CI

on: [push]

env:
  INPUT_TZ1: Asia
  INPUT_TZ2: Shanghai

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-2019
            cuda: "11.4.2"
            visual_studio: "Visual Studio 16 2019"
  
    runs-on: windows-latest
    
    steps:
    
    - name: Install CUDA
      env: 
        cuda: ${{ matrix.cuda }}
        visual_studio: ${{ matrix.visual_studio }}
      shell: powershell
      run: .\scripts\actions\install_cuda_windows.ps1

    - name: nvcc check
      shell: powershell
      run: |
        nvcc -V
        ls $env:CUDA_PATH
        ls $env:CUDA_PATH\bin
        ls $env:CUDA_PATH\include
        
    - name: Get current date
      id: get_datetime
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Print the datetime
      run: |
        echo ${{ steps.get_datetime.outputs.date }}-${{ matrix.os }}
      shell: bash
      
