name: CI

on: [push]

env:
  INPUT_TZ1: Asia
  INPUT_TZ2: Shanghai

jobs:
  build:
    strategy:
      matrix:
          os: [windows-2019]
  
    runs-on: windows-latest
    
    steps:
    
    - uses: Jimver/cuda-toolkit@v0.2.4
      id: cuda-toolkit
      with:
        cuda: '11.4.0'
